### ISSUE TITLE
Feature Request: Capslock to close window

### ISSUE THREAD

**Issue by ochief** [BenjaminKobjolke/FastKeyboardWindowSwitcher#1]
If possible it would be fantastic if once the menu is open clicking CAPSLOCK would close the menu, rather than/as well as using ESC

**Comment by ochief** [comment]
Didn't want to close this in case you were interested,

Amended the hotkey to;
```
~capslock:: 
    IfWinActive, Window Switcher
        send {esc}
    else
        GoSub, HotkeyAction
    return
```
then added the following input;

```
    if ErrorLevel = EndKey:capslock 
    { 
        Gui, cancel  
        send {capslock}
        break 
    } 
```

**Comment by strassenphilosophie** [comment]
I never answered your question but I implemented the feature a while ago.

**Comment by BenjaminKobjolke** [comment]
Has been added a while ago :)
