### ISSUE TITLE
Handling multi monitors on different planes

### ISSUE THREAD

**Issue by ochief** [BenjaminKobjolke/FastKeyboardWindowSwitcher#2]
I had an issue with the GUI not being centered on my second monitor which is stacked vertically rather than horizontally. A bit of googling and I fixed it by amending **CoordYCenterScreen** to the following;

```
CoordYCenterScreen(HeightofGUI,ScreenNumber)
{
	SysGet, Mon1, Monitor, %ScreenNumber%
	return ((Mon1Bottom-Mon1Top - 30 - HeightofGUI ) / 2) + Mon1Top
}
```

**Comment by BenjaminKobjolke** [comment]
I changed how the window is created in the latest version.
Can you please try that one.

You can also adjust the window size via settings.ini
Have a look at the readme and at settings_example.ini
### [gui]

#### spacing
`spacingHorizontal=10`
The spacing of the iSwitch window from the left your screen in percent.
10 means the window will start 10% from the left the active screen and will also keep the same distance from the right side.

`spacingVertical=10`
The spacing of the iSwitch window from the top your screen in percent.
10 means the window will start 10% from the top the active screen and will also keep the same distance from the bottom side.

**Comment by BenjaminKobjolke** [comment]
I created a new release that should fix the problem, please test

**Comment by ochief** [comment]
That worked, thanks
